[build]
  publish = "public"
  command = ""   # билд не нужен — просто отдать public

[functions]
  node_bundler = "esbuild"

# /api/* -> Netlify Function
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback для роутинга
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
